COMPILER = gcc
FLAGS = -O2 -ftrapv -fsanitize=undefined -Wall -Werror -Wformat-security -Wignored-qualifiers -Winit-self -Wswitch-default -Wfloat-equal -Wshadow -Wpointer-arith -Wtype-limits -Wempty-body -Wlogical-op -Wstrict-prototypes -Wold-style-declaration -Wold-style-definition -Wmissing-parameter-type -Wmissing-field-initializers -Wnested-externs -Wno-pointer-sign -Wcast-qual -Wwrite-strings -std=gnu11 -g -lm

SRCS=$(wildcard *.c)

OBJS=$(SRCS:.c=)

all: $(OBJS)

test: $(SRC)
	gcc -o $@ $^ $(FLAGS)

clean:
	rm -f test